config/routes.rb
ProyectoSalasensayo::Application.routes.draw do
  resources :salas 

  root :to => "Inicio#index"

  match "/auth/:provider/callback", :to => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/listview" => "Salas#index"
  match "/mapview" => "Salas#map"
  match "/search" => "Salas#search"
  match "/salas/:id/like", :to => "salas#like", as: "like_sala"
  match "/reservas/:sala_id/book", :to => "reservas#book", as: "book_sala"

end

app/models/sala.rb
class Sala < ActiveRecord::Base
	acts_as_voteable
	has_and_belongs_to_many :instrumentos
	has_many :reservas

	def self.search(nombre)
	  if nombre
	    find(:all, :conditions => ['nombre LIKE ?', "%#{nombre}%"])
	  else
	    find(:all)
	  end
	end
end

app/controllers/salas_controller.rb
class SalasController < ApplicationController
  # GET /salas
  # GET /salas.json
  def index
    if(params[:nombre])
      @salas = Sala.search(params[:nombre])   
    elsif(params[:instrumentos])
      @salas = Sala.search("rm")    
    else
      @salas = Sala.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @salas }
    end
  end

  # GET /salas/1
  # GET /salas/1.json
  def show
    current_user = User.find(session[:user_id])

    @sala = Sala.find(params[:id])
    @reservado = Reserva.where(:sala_id => @sala.id, :user_id => current_user.id).count > 0 ? true : false

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sala }
    end
  end

  # GET /salas/new
  # GET /salas/new.json
  def new
    @sala = Sala.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sala }
    end
  end

  # GET /salas/1/edit
  def edit
    @sala = Sala.find(params[:id])
  end

  # POST /salas
  # POST /salas.json
  def create
    current_user = User.find(session[:user_id])

    @sala = Sala.new(params[:sala])
    @sala.creator_id = current_user.id

    respond_to do |format|
      if @sala.save
        format.html { redirect_to @sala, notice: 'Sala was successfully created.' }
        format.json { render json: @sala, status: :created, location: @sala }
      else
        format.html { render action: "new" }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /salas/1
  # PUT /salas/1.json
  def update
    @sala = Sala.find(params[:id])

    respond_to do |format|
      if @sala.update_attributes(params[:sala])
        format.html { redirect_to @sala, notice: 'Sala was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salas/1
  # DELETE /salas/1.json
  def destroy
    @sala = Sala.find(params[:id])
    @sala.destroy

    respond_to do |format|
      format.html { redirect_to salas_url }
      format.json { head :no_content }
    end
  end

  # POST /search
  # POST /search.json
  def search
    @instrumentos = Instrumento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @salas }
    end
  end

  # POST /map
  # POST /map.json
  def map
  	if(params[:nombre])
	    @salas = Sala.search(params[:nombre])
	  else
    	@salas = Sala.all
  	end

    respond_to do |format|
      format.html # map.html.erb
      format.json { render json: @salas }
    end
  end

  def like
    begin
      @sala = Sala.find(params[:id])
      current_user.vote_for(@sala)
      redirect_to sala_path(@sala)
    end
  end

end

app/helpers/salas_helper.rb
module SalasHelper
end

app/views/salas/_form.html.erb
<%= form_for(@sala) do |f| %>
  <% if @sala.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sala.errors.count, "error") %> prohibited this sala from being saved:</h2>
      <ul>
      <% @sala.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br />
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :costo %><br />
    <%= f.text_field :costo %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br />
    <%= f.text_field :lng %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salas/edit.html.erb
<% content_for :header do %>
	<%= link_to 'Back', salas_path, "data-icon" => "back", "data-theme" => "b", "data-ajax" => "false" %>
	<h1>New sala</h1>
<% end %>
<%= render 'form' %>

app/views/salas/index.html.erb
<% content_for :header do %>
  <%= link_to 'Back', "/", "data-icon" => "back", "data-theme" => "b" %>
  <h1>List View</h1>
  <%= link_to "New Sala", new_sala_path, "data-role" => "button", "data-icon" => "plus", "data-theme" => "b", "data-ajax" => "false", "class" => "ui-btn-right" %>
<% end %>
<ul data-role="listview" data-inset="true" data-filter="true">
  <% @salas.each do |sala| %>
  <li>
    <a href="/salas/<%= sala.id %>" data-ajax="false">
      <h3><%= sala.nombre %></h3>
      <p><strong><%= sala.direccion %></strong></p>
      <p><%= sala.telefono %></p>
      <p><%= sala.email %></p>
      <% if sala.instrumentos.count > 0 %>
      <p><strong>Instrumentos:</strong></p>
      <ul>
      <% sala.instrumentos.each do |instrumento| %>
        <li><p><%= instrumento.nombre %></p></li>
      <%end%>
      </ul>
      <% end %>
    </a>
    <% if current_user.id == sala.creator_id %>
      <%= link_to 'Edit', edit_sala_path(sala), "data-icon" => "gear", "data-ajax" => "false" %>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/salas/map.html.erb
<% content_for :header do %>
  <%= link_to 'Back', "/", "data-icon" => "back", "data-theme" => "b" %>
  <h1>Map View</h1>
<% end %>
<% if @salas.count > 0 %>
<div class="map_content">
  <div id="map_canvas"></div>
</div>
<% else %>
<div class="ui-bar ui-bar-e">
	<h3 style="float:left; margin-top:8px;">No se encontraron salas.</h3>
	<p style="clear:both; font-size:85%; margin-bottom:8px;">
		Prueba ingrsando a la opción 'List View' del Home de la aplicación.
	</p>
</div>
<% end %>
<% if @salas.count > 0 %>
<script type="text/javascript">
  var GMaps = google.maps;
  var map, infowindow;

  function setupMap(mapLatlng, mapZoom, showOverviewControl) {
    var myOptions = {
      scrollwheel: false,
      zoom: mapZoom,
      center: mapLatlng,
      mapTypeId: GMaps.MapTypeId.ROADMAP,
      overviewMapControl: showOverviewControl,
			scaleControl : true,
      zoomControl: true,
      zoomControlOptions: {
        style: GMaps.ZoomControlStyle.SMALL,
        position: GMaps.ControlPosition.LEFT_TOP
      },
			navigationControlOptions : {
				position : GMaps.ControlPosition.RIGHT
			}
    };
    map = new GMaps.Map(document.getElementById("map_canvas"), myOptions);
  }

	function createMarkers() {
		<% @salas.each do |sala| %>
    var markerLatlng = new GMaps.LatLng("<%= sala.lat %>", "<%= sala.lng %>");
    var infoMarker = createMarker(markerLatlng, "<%= sala.nombre %>");
    var infoContent = "<div class='infowindow'>" + 
		                    "<h3><%= sala.nombre %></h3>" + 
		                    "<p><b>Dirección:</b> <%= sala.direccion %></p>" + 
		                    "<p><b>Teléfono:</b> <%= sala.telefono %></p>" + 
		                    "<p><b>E-mail:</b> <%= sala.email %></p>" + 
		                  "</div>";
    createInfoWindow(infoMarker, infoContent);
    <% end %>
	}

  function createMarker(markerLatlng, markerTitle) {
    var marker = new GMaps.Marker({
      position: markerLatlng, 
      map: map,
      title: markerTitle
    });
    marker.setAnimation(GMaps.Animation.DROP);
    return marker;
  }

  function createInfoWindow(infoMarker, infoContent) {
		infoMarker.infowindow = new GMaps.InfoWindow({
			content : infoContent
		});
		GMaps.event.addListener(infoMarker, 'click', function() {
			if(infowindow != null) {
				infowindow.close();
			}
			infoMarker.infowindow.open(map, infoMarker);
			infowindow = infoMarker.infowindow;
		});
  }

  function initialize() {
    var lat = "-12.00842782682728";
    var lng = "-77.02789306640625";
    var myLatlng = new GMaps.LatLng(lat, lng);
    setupMap(myLatlng, 12, true);
		createMarkers();
  }

  // Initialize the map when the jQuery Mobile pageshow event is triggered
  $('.details-page').live("pageshow", function() {
  	<% if @salas.count > 0 %>
    if (map == null) {
      initialize();
    }
    <% end %>
  });
</script>
<% end %>

app/views/salas/new.html.erb
<% content_for :header do %>
	<%= link_to 'Back', salas_path, "data-icon" => "back", "data-theme" => "b", "data-ajax" => "false" %>
	<h1>New sala</h1>
<% end %>
<%= render 'form' %>

app/views/salas/search.html.erb
<div data-role="page">
	<div data-role="header">
    <%= link_to 'Back', "./", "data-icon" => "back", "data-theme" => "b", "data-ajax" => "false" %>
	  <h1>Search</h1>

	</div><!-- /header -->
	<div data-role="content">
		<%= form_tag "listview", :method => 'get' do %>
			<p>
				<%= label_tag(:nombre, "Nombre") %>
				<%= text_field_tag :nombre %>
			</p>
			
			<p>
				 <fieldset data-role="controlgroup", data-type="horizontal">
				<% @instrumentos.each do |instrumento| %>
				<%= label_tag(:instrumentos[instrumento.id], instrumento.nombre) %>
				<%= check_box_tag(:instrumentos[instrumento.id], instrumento.nombre) %>
				<%end%>
				</fieldset>
			</p>
			
			<%= submit_tag "Search" %>
		<% end %>
  </div><!-- /content -->
</div><!-- /page -->

app/views/salas/show.html.erb
<% content_for :header do %>
  <%= link_to 'Back', salas_path, "data-icon" => "back", "data-theme" => "b", "data-ajax" => "false" %>
  <h1><%= @sala.nombre %></h1>
  <% if current_user.id == @sala.creator_id %>
    <%= link_to 'Edit', edit_sala_path, "data-icon" => "gear", "data-ajax" => "false" %>
  <% else %>
    <% if !@reservado %>
      <%= link_to 'Reservar', "/reservas/" + @sala.id.to_s + "/book", "data-icon" => "gear", "data-ajax" => "false" %>
    <% else %>
      <%= link_to 'Reservado', "#", "data-theme" => "e", "data-icon" => "check" %>
    <% end %>
  <% end %>
<% end %>
<div>
  <% if Vote.where(:voter_id => current_user.id, :voteable_id => @sala.id, ).count > 0 %>
    <div data-role="button", data-inline="true">
    <% if Vote.where(:voteable_id => @sala.id).count > 1 %>
        <%= Vote.where(:voteable_id => @sala.id).count %> persona(s) la recomienda(n)
    <%else%>
        Tu lo recomiendas
    <% end %>
    </div>
  <% else %>
    <%= link_to 'Recomendar', like_sala_path(@sala), :method => :sala, "data-role" => "button", "data-icon" => "plus", "data-inline" => "true", "data-theme" => "b"%>
    <div data-role="button", data-inline="true"> <%= Vote.where(:voteable_id => @sala.id).count %> persona(s) la recomienda(n) </div>
  <% end %>
</div><!-- /recomendar --> 
<div>
  <p id="notice"><%= notice %></p>
  <p>
    <b>Direccion:</b>
    <%= @sala.direccion %>
  </p>
  <p>
    <b>Telefono:</b>
    <%= @sala.telefono %>
  </p>
  <p>
    <b>Email:</b>
    <%= @sala.email %>
  </p>
  <p>
    <b>Costo:</b>
    <%= @sala.costo %>
  </p>
  <% if @sala.instrumentos.count > 0 %>
  <p><strong>Instrumentos:</strong></p>
  <ul>
  	<% @sala.instrumentos.each do |instrumento| %>
    <li><p><%= instrumento.nombre %></p></li>
  	<% end %>
  </ul>
  <% end %>
  <% if current_user.id == @sala.creator_id %>
	  <% if @sala.reservas.count > 0 %>
	  <p><strong>Reservas:</strong></p>
	  <ul>
	  	<% @sala.reservas.each do |reserva| %>
	    <li><p>Reservado el <%= reserva.created_at %> por <%= reserva.user.name %> [ <%= reserva.user.nick %> ]</p></li>
	  	<% end %>
	  </ul>
	  <% end %>
  <% end %>
</div>
<div class="map_content">
	<div id="map_canvas" style="margin-top: 15px; height: 400px; width: 400px;"></div>
</div>
<script type="text/javascript">
  var GMaps = google.maps;
  var map, marker, infowindow;

  function setupMap(mapLatlng, mapZoom, showOverviewControl) {
    var myOptions = {
      scrollwheel: false,
      zoom: mapZoom,
      center: mapLatlng,
      mapTypeId: GMaps.MapTypeId.ROADMAP,
      overviewMapControl: showOverviewControl,
      scaleControl : true,
      zoomControl: true,
      zoomControlOptions: {
        style: GMaps.ZoomControlStyle.SMALL,
        position: GMaps.ControlPosition.LEFT_TOP
      },
      navigationControlOptions : {
        position : GMaps.ControlPosition.RIGHT
      }
    };
    map = new GMaps.Map(document.getElementById("map_canvas"), myOptions);
  }

  function createMarker(markerLatlng, markerTitle) {
    marker = new GMaps.Marker({
      position: markerLatlng, 
      map: map,
      title: markerTitle
    });
    marker.setAnimation(GMaps.Animation.BOUNCE);
  }

  function createInfoWindow(infoContent) {
    infowindow = new GMaps.InfoWindow({
      content: infoContent
    });
    GMaps.event.addListener(marker, 'click', function() {
      infowindow.open(map, marker);
    });
    /*infowindow.open(map, marker);*/
  }

  function initialize() {
    var lat = "<%= @sala.lat %>";
    var lng = "<%= @sala.lng %>";
    var title = "<%= @sala.nombre %>";
    var content = "<div class='infowindow'>" + 
                    "<h3><%= @sala.nombre %></h3>" + 
                    "<p><b>Dirección:</b> <%= @sala.direccion %></p>" + 
                    "<p><b>Teléfono:</b> <%= @sala.telefono %></p>" + 
                    "<p><b>E-mail:</b> <%= @sala.email %></p>" + 
                  "</div>";
    var myLatlng = new GMaps.LatLng(lat, lng);
    setupMap(myLatlng, 15, true);
    createMarker(myLatlng, title);
    createInfoWindow(content);
  }

  // Initialize the map when the jQuery Mobile pageshow event is triggered
  $('.details-page').live("pageshow", function() {
    if (map == null) {
      initialize();
    }
  });
</script>